export interface Product {
  id: string;
  name: string;
  composition: string;
  mrp: number;
  pricePerStrip: number;
  stripSize: number;
  category: string;
  description: string;
  image: string;
}

export const products: Product[] = [
  {
    id: "prod-001",
    name: "ESORIK-D CAPS",
    composition: "Esomeprazole 40mg + Domperidone 30mg",
    mrp: 108,
    pricePerStrip: 108,
    stripSize: 10,
    category: "Capsule",
    description: "For acid reflux and GERD",
    image: "https://i.postimg.cc/mP3Fr2cq/esorik-D.jpg",
  },
  {
    id: "prod-002",
    name: "CEFNIK-200LB TAB",
    composition: "Cefixime 200mg + Lactobacillus",
    mrp: 180,
    pricePerStrip: 180,
    stripSize: 10,
    category: "Tablet",
    description: "Antibiotic with probiotic",
    image: "https://i.postimg.cc/mPWHRFrr/cefnik-200-lb.jpg",
  },
  {
    id: "prod-003",
    name: "MONTARIK-LC TAB",
    composition: "Montelukast 10mg + Levocetirizine 5mg",
    mrp: 135,
    pricePerStrip: 135,
    stripSize: 10,
    category: "Tablet",
    description: "For allergies and asthma",
    image: "https://i.postimg.cc/yDhSNYgK/montarik-lc.jpg",
  },
  {
    id: "prod-005",
    name: "CDM-60K SACHET",
    composition: "Cholecalciferol 60000 IU",
    mrp: 38,
    pricePerStrip: 38,
    stripSize: 4,
    category: "Sachet",
    description: "Vitamin D3 supplement",
    image: "https://i.postimg.cc/MvQQhYz6/cdm-60k.jpg",
  },
  {
    id: "prod-006",
    name: "BIORIK PRO CAPS",
    composition: "Probiotic Complex",
    mrp: 150,
    pricePerStrip: 150,
    stripSize: 10,
    category: "Capsule",
    description: "Gut health supplement",
    image: "https://i.postimg.cc/YhWWJxt2/biorik-pro.jpg",
  },
  {
    id: "prod-007",
    name: "OFLARIK-200 TAB",
    composition: "Ofloxacin 200mg",
    mrp: 69,
    pricePerStrip: 69,
    stripSize: 10,
    category: "Tablet",
    description: "Antibiotic for bacterial infections",
    image: "https://i.postimg.cc/xXGbdTJf/oflarik-200.jpg",
  },
  {
    id: "prod-008",
    name: "RIKVITA SYRUP",
    composition: "Multivitamin & Minerals",
    mrp: 159.8,
    pricePerStrip: 159.8,
    stripSize: 1,
    category: "Syrup",
    description:
      "Complete nutritional supplement (200ml bottle)",
    image: "https://i.postimg.cc/xk0NNDMq/rikvita-syr.jpg",
  },
  {
    id: "prod-009",
    name: "CEFNIK-O DRY SYRUP",
    composition: "Cefixime 50mg/5ml",
    mrp: 96,
    pricePerStrip: 96,
    stripSize: 1,
    category: "Syrup",
    description:
      "Antibiotic suspension for children (30ml bottle)",
    image: "https://i.postimg.cc/5XWC1Ftw/cefnik-o-syr.jpg",
  },
  {
    id: "prod-010",
    name: "CEFNIK-O TAB",
    composition: "Cefixime 200mg + Ofloxacin 200mg",
    mrp: 225,
    pricePerStrip: 225,
    stripSize: 10,
    category: "Tablet",
    description: "Combination antibiotic",
    image: "https://i.postimg.cc/75r2DTLS/cefnik-o-syrup.jpg",
  },
  {
    id: "prod-011",
    name: "AZIRIK-250 TAB",
    composition: "Azithromycin 250mg",
    mrp: 78.21,
    pricePerStrip: 78.21,
    stripSize: 6,
    category: "Tablet",
    description: "Antibiotic for respiratory infections",
    image: "https://i.postimg.cc/rK01qkCH/azirik-250.jpg",
  },
  {
    id: "prod-012",
    name: "AZIRIK-500 TAB",
    composition: "Azithromycin 500mg",
    mrp: 72,
    pricePerStrip: 72,
    stripSize: 5,
    category: "Tablet",
    description: "High-strength antibiotic",
    image: "https://i.postimg.cc/dLyyz9JJ/azirik-500.jpg",
  },
  {
    id: "prod-013",
    name: "COFRIK-D SYRUP",
    composition: "Dextromethorphan + Chlorpheniramine",
    mrp: 109,
    pricePerStrip: 109,
    stripSize: 1,
    category: "Syrup",
    description: "Cough suppressant (100ml bottle)",
    image: "https://i.postimg.cc/68xvwGQ1/cofrik-D.jpg",
  },
  {
    id: "prod-014",
    name: "DEACT TAB",
    composition: "Diclofenac + Paracetamol + Serratiopeptidase",
    mrp: 69,
    pricePerStrip: 69,
    stripSize: 10,
    category: "Tablet",
    description: "Pain and inflammation relief",
    image: "https://i.postimg.cc/k2Nt5XVh/deact.jpg",
  },
  {
    id: "prod-015",
    name: "COFRIK EXPECTORANT SYRUP",
    composition: "Guaifenesin + Ambroxol",
    mrp: 108,
    pricePerStrip: 108,
    stripSize: 1,
    category: "Syrup",
    description:
      "Expectorant for productive cough (100ml bottle)",
    image: "https://i.postimg.cc/68xvwGQV/cofrik.jpg",
  },
  {
    id: "prod-016",
    name: "ORDIC GEL",
    composition: "Diclofenac Diethylamine + Methyl Salicylate",
    mrp: 105,
    pricePerStrip: 105,
    stripSize: 1,
    category: "Gel",
    description: "Topical pain relief gel (30g tube)",
    image: "https://i.postimg.cc/2qzLLRhp/ordic-gel.jpg",
  },
  
  {
    id: "prod-018",
    name: "BRECET SYRUP",
    composition: "Cetirizine 5mg/5ml",
    mrp: 73,
    pricePerStrip: 73,
    stripSize: 1,
    category: "Syrup",
    description: "Antihistamine for allergies (60ml bottle)",
    image: "https://i.postimg.cc/crnnVcd0/brecet.jpg",
  },
  {
    id: "prod-019",
    name: "ULTRA ZEAL TAB",
    composition: "Multivitamin + Multimineral + Antioxidants",
    mrp: 119.7,
    pricePerStrip: 119.7,
    stripSize: 15,
    category: "Tablet",
    description: "Complete wellness supplement",
    image: "https://i.postimg.cc/R6h3G7gX/ultra-zeal.jpg",
  },
  {
    id: "prod-020",
    name: "NEURORIK PLUS TAB",
    composition:
      "Methylcobalamin + Alpha Lipoic Acid + Folic Acid",
    mrp: 159,
    pricePerStrip: 159,
    stripSize: 10,
    category: "Tablet",
    description: "Nerve health supplement",
    image: "https://i.postimg.cc/Hr07Lscd/neurorik-plus.jpg",
  },
  {
    id: "prod-021",
    name: "RIKY GEL SYRUP",
    composition:
      "Aluminium Hydroxide + Magnesium Hydroxide + Simethicone",
    mrp: 95,
    pricePerStrip: 95,
    stripSize: 1,
    category: "Syrup",
    description:
      "For acidity and digestive problems, provides relief from heartburn and gas (170ml bottle)",
    image: "https://i.postimg.cc/qtk66VyJ/rekygel.jpg",
  },
];